"""add restoration table

Revision ID: 2026052400
Revises: f2ee81a56fee
Create Date: 2026-04-26 11:44:11.805803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2026052400'
down_revision: Union[str, Sequence[str], None] = 'f2ee81a56fee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restoration',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('server_id', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('WORLD', 'DIMENSION', 'REGIONS', 'CHUNKS', name='restorationtype'), nullable=False),
    sa.Column('source_snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('safety_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('selection_json', sa.TEXT(), nullable=False),
    sa.Column('is_rollback', sa.Boolean(), nullable=False),
    sa.Column('initiated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCEEDED', 'FAILED', 'INTERRUPTED', name='restorationstatus'), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restoration_server_id'), 'restoration', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restoration_server_id'), table_name='restoration')
    op.drop_table('restoration')
    # ### end Alembic commands ###
