"""Remove last_seen from player table and add index for last_seen calculation

Revision ID: ba4b4a1fb5a8
Revises: 
Create Date: 2025-10-25 14:40:42.906622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4b4a1fb5a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'last_seen')
    op.create_index('idx_player_session_player_left_at', 'player_session', ['player_db_id', 'left_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_player_session_player_left_at', table_name='player_session')
    op.add_column('player', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
