"""Add created_at field to User model

Revision ID: c3baaa5067b4
Revises: 
Create Date: 2025-09-04 23:28:43.299805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3baaa5067b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support adding columns with non-constant defaults
    # Add the column as nullable first, then update existing records
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    
    # Update existing records with current timestamp
    connection = op.get_bind()
    connection.execute(
        sa.text("UPDATE user SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
