"""Add server template support

Revision ID: f2ee81a56fee
Revises: ba4b4a1fb5a8
Create Date: 2026-01-31 23:58:42.860424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ee81a56fee'
down_revision: Union[str, Sequence[str], None] = 'ba4b4a1fb5a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('yaml_template', sa.TEXT(), nullable=False),
    sa.Column('variables_json', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_template_name'), 'server_template', ['name'], unique=True)
    op.add_column('server', sa.Column('template_id', sa.Integer(), nullable=True))
    op.add_column('server', sa.Column('template_snapshot_json', sa.TEXT(), nullable=True))
    op.add_column('server', sa.Column('variable_values_json', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'variable_values_json')
    op.drop_column('server', 'template_snapshot_json')
    op.drop_column('server', 'template_id')
    op.drop_index(op.f('ix_server_template_name'), table_name='server_template')
    op.drop_table('server_template')
    # ### end Alembic commands ###
