"""Server template module for template-based server creation."""

from .manager import TemplateManager
from .models import (
    SYSTEM_RESERVED_VARIABLES,
    SYSTEM_VARIABLE_NAMES,
    AvailablePortsResponse,
    BoolVariableDefinition,
    EnumVariableDefinition,
    FloatVariableDefinition,
    IntVariableDefinition,
    StringVariableDefinition,
    TemplateCreateRequest,
    TemplateListItem,
    TemplatePreviewRequest,
    TemplatePreviewResponse,
    TemplateResponse,
    TemplateSchemaResponse,
    TemplateUpdateRequest,
    VariableDefinition,
    VariableType,
    cast_variables_json,
)

__all__ = [
    "TemplateManager",
    "VariableType",
    "IntVariableDefinition",
    "FloatVariableDefinition",
    "StringVariableDefinition",
    "EnumVariableDefinition",
    "BoolVariableDefinition",
    "VariableDefinition",
    "SYSTEM_RESERVED_VARIABLES",
    "SYSTEM_VARIABLE_NAMES",
    "TemplateCreateRequest",
    "TemplateUpdateRequest",
    "TemplateResponse",
    "TemplateListItem",
    "TemplateSchemaResponse",
    "AvailablePortsResponse",
    "TemplatePreviewRequest",
    "TemplatePreviewResponse",
    "cast_variables_json",
]
