import asyncio

from app.config import ResticSettings
from app.dynamic_config.configs.snapshots import WorldRestoreConfig
from app.runtime import UNINITIALIZED
from app.runtime_resources import current_runtime
from tests.support.runtime import (
    patch_runtime_resource,
    patch_settings,
    replace_runtime_resource,
)
from tests.support.tasks import task_result, wait_task

"""
End-to-end tests for snapshot API endpoints using real restic commands.

These tests use actual restic operations and FastAPI TestClient to ensure the snapshot
management system works correctly with real API endpoints. Tests create temporary
directories and repositories to avoid affecting real data, with MC server directory structure.

IMPORTANT: These tests require restic to be installed on the system.
"""

import subprocess
import tempfile
from contextlib import contextmanager
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from fastapi.testclient import TestClient

from app.config import get_settings
from app.main import api_app
from app.minecraft import MCServerStatus
from app.snapshots import ResticClient, SnapshotService
from app.utils.exec import exec_command


def _scope(server_id=None, paths=None):
    if paths:
        return {"kind": "paths", "server_id": server_id, "paths": [path.lstrip("/") or "." for path in paths]}
    return {"kind": "server", "server_id": server_id} if server_id else {"kind": "global"}


def _restore_safety_snapshot_id(client, response) -> str:
    return task_result(client, response)["safety_snapshot_id"]


def _preview_result(client, response):
    result = task_result(client, response)
    base = "/snapshots/previews/" + result["preview_id"]
    headers = {"Authorization": "Bearer test_master_token"}
    actions, cursor = [], 0
    while cursor is not None:
        page = client.get(base + "/actions", params={"cursor": cursor}, headers=headers)
        assert page.status_code == 200, page.text
        actions.extend(page.json()["actions"])
        cursor = page.json()["next_cursor"]
    task_result(client, client.delete(base, headers=headers))
    return {**result, "actions": actions}


@pytest.fixture(autouse=True)
async def registered_server(mock_instance):
    from app.db.metadata import Base
    from app.operations.journal import OperationJournal
    from app.servers.models import Server

    runtime = current_runtime()
    async with runtime.database.engine.begin() as connection:
        await connection.run_sync(Base.metadata.create_all)
    async with runtime.database.session_factory() as session:
        session.add(Server(server_id=mock_instance[0]))
        await session.commit()
    runtime.journal = OperationJournal(runtime.database.session_factory)


# Helper function to check if restic is available
def check_restic_available():
    """Check if restic command is available"""
    try:
        result = subprocess.run(
            [str(get_settings().restic_binary_path), "version"],
            capture_output=True,
            text=True,
            timeout=5, check=False,
        )
        return result.returncode == 0
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return False


# Skip all tests if restic is not available
pytestmark = pytest.mark.skipif(
    not check_restic_available(),
    reason="restic command not available - install restic to run these tests",
)


class MockMCInstance:
    """Mock MCInstance for testing with proper MC server structure."""

    def __init__(self, server_id: str, base_path: Path):
        self.server_id = server_id
        self.base_path = base_path
        self.project_path = base_path / server_id

    def get_name(self) -> str:
        return self.server_id

    async def get_status(self) -> MCServerStatus:
        return MCServerStatus.EXISTS

    def get_project_path(self) -> Path:
        """Return the project path."""
        return self.project_path

    def get_data_path(self) -> Path:
        """Return the data path."""
        return self.project_path / "data"

    async def exists(self):
        """Return True to indicate server exists."""
        return True

    def setup_mc_server_structure(self):
        """Create realistic MC server file and directory structure."""
        # Create base directories
        self.get_data_path().mkdir(parents=True, exist_ok=True)
        (self.project_path / "compose.yaml").write_text("services: {}\n")

        # Create MC server configuration files
        (self.get_data_path() / "server.properties").write_text(
            """#Minecraft server properties
#Generated by MC Admin
server-port=25565
gamemode=survival
difficulty=normal
max-players=20
online-mode=true
level-name=world
motd=Test MC Server
allow-flight=false
spawn-protection=16
"""
        )

        (self.get_data_path() / "bukkit.yml").write_text(
            """settings:
  allow-end: true
  warn-on-overload: true
  permissions-file: permissions.yml
  update-folder: update
  plugin-profiling: false
  connection-throttle: 4000
spawn-limits:
  monsters: 70
  animals: 15
  water-animals: 5
  ambient: 15
"""
        )

        (self.get_data_path() / "paper.yml").write_text(
            """settings:
  max-joins-per-tick: 3
  track-plugin-scoreboards: false
  suggest-player-names-when-null-tab-completions: true
world-settings:
  default:
    anti-xray:
      enabled: true
      engine-mode: 1
"""
        )

        (self.get_data_path() / "ops.json").write_text("[]")
        (self.get_data_path() / "whitelist.json").write_text("[]")
        (self.get_data_path() / "banned-players.json").write_text("[]")
        (self.get_data_path() / "banned-ips.json").write_text("[]")

        # Create world directory with typical MC world structure
        world_path = self.get_data_path() / "world"
        world_path.mkdir(exist_ok=True)
        (world_path / "level.dat").write_bytes(
            b"\x1f\x8b\x08\x00\x00\x00\x00\x00"
        )  # Fake NBT data
        (world_path / "session.lock").write_bytes(b"\x00\x00\x00\x00\x00\x00\x00\x01")

        # Create region directory with fake region files
        region_path = world_path / "region"
        region_path.mkdir(exist_ok=True)
        (region_path / "r.0.0.mca").write_bytes(b"\x00" * 4096)  # Fake region file
        (region_path / "r.0.1.mca").write_bytes(b"\x00" * 8192)  # Different size

        # Create world subdirectories
        for subworld in ["DIM-1", "DIM1"]:
            subworld_path = world_path / subworld
            subworld_path.mkdir(exist_ok=True)
            (subworld_path / "region").mkdir(exist_ok=True)

        # Create plugins directory with sample plugins
        plugins_path = self.get_data_path() / "plugins"
        plugins_path.mkdir(exist_ok=True)
        (plugins_path / "EssentialsX.jar").write_bytes(
            b"\x50\x4b\x03\x04" + b"\x00" * 100
        )  # Fake JAR
        (plugins_path / "WorldEdit.jar").write_bytes(
            b"\x50\x4b\x03\x04" + b"\x00" * 150
        )  # Fake JAR

        # Plugin configs
        (plugins_path / "Essentials").mkdir(exist_ok=True)
        (plugins_path / "Essentials" / "config.yml").write_text(
            """essentials:
  command-cooldowns:
    home: 10
    tpa: 5
"""
        )

        # Create cache and temp directories
        (self.get_data_path() / "cache").mkdir(exist_ok=True)
        (self.get_data_path() / "cache" / "mojang_1.20.4.jar").write_bytes(
            b"\x00" * 1000
        )

        return self


@contextmanager
def mock_snapshot_dependencies_setup(
    instance,
    temp_restic_repo: Path,
    restic_password: str | None = "test-password",
    ignored_paths: list[str] | None = None,
):
    """Context manager for mocking snapshot dependencies.

    Args:
        instance: The MockMCInstance to use for testing
        temp_restic_repo: Path to temporary restic repository
        restic_password: Password for restic repository (None for no password)
        ignored_paths: ignored_paths dynamic config seen by the service
    """
    # Create mock dynamic config
    mock_time_restriction = MagicMock()
    mock_time_restriction.enabled = True
    mock_time_restriction.before_seconds = 30
    mock_time_restriction.after_seconds = 60

    mock_snapshots_config = MagicMock()
    mock_snapshots_config.time_restriction = mock_time_restriction
    mock_snapshots_config.ignored_paths = ignored_paths or []
    mock_snapshots_config.world_restore = WorldRestoreConfig()

    mock_config = MagicMock()
    mock_config.snapshots = mock_snapshots_config

    # A real SnapshotService against the test repository; the instance
    # provider drives ignored-path resolution.
    instance_provider = MagicMock()
    instance_provider.get_all_instances = AsyncMock(return_value=[instance])
    test_snapshot_service = SnapshotService(
        ResticClient(
            repository_path=str(temp_restic_repo),
            password=restic_password,
        ),
        instance_provider,
    )

    with (
        patch_runtime_resource('docker_mc_manager') as mock_manager,
        patch_settings() as mock_settings,
        patch_settings() as mock_dep_settings,
        patch_runtime_resource('dynamic_configuration', mock_config),
        patch.object(current_runtime().restart_scheduler, 'get_backup_minutes', return_value=set()),  # No backup jobs by default
        patch_runtime_resource('snapshot_service', test_snapshot_service),
    ):
        # Mock settings for snapshots
        mock_settings.server_path = instance.base_path
        mock_settings.restic = ResticSettings(repository_path=str(temp_restic_repo), password=restic_password)

        # Mock settings for dependencies (master token)
        mock_dep_settings.master_token = "test_master_token"

        # Mock MC managers
        mock_manager.get_instance.return_value = instance
        # The restore endpoint walks every known instance to invalidate map
        # tiles after a restore — return the single test instance here so
        # the await doesn't blow up on a bare MagicMock.
        mock_manager.get_all_instances = AsyncMock(return_value=[instance])

        replace_runtime_resource(current_runtime(), "snapshot_commands", UNINITIALIZED)
        yield


class TestSnapshotEndpoints:
    """End-to-end tests for snapshot API endpoints using real restic operations."""

    @pytest.fixture
    def client(self):
        """Create test client."""
        with TestClient(api_app) as client:
            yield client

    @pytest.fixture
    def temp_server_dir(self):
        """Create temporary directory for MC server."""
        with tempfile.TemporaryDirectory(prefix="mc_snapshot_test_") as temp_dir:
            yield Path(temp_dir)

    @pytest.fixture
    def temp_restic_repo(self):
        """Create temporary directory for restic repository."""
        with tempfile.TemporaryDirectory(prefix="restic_repo_test_") as temp_dir:
            yield Path(temp_dir)

    @pytest.fixture
    def mock_instance(self, temp_server_dir):
        """Create mock instance with realistic MC server structure."""
        server_id = "test_server"
        instance = MockMCInstance(server_id, temp_server_dir)
        instance.setup_mc_server_structure()
        return server_id, instance

    @pytest.fixture
    async def initialized_restic_repo(self, temp_restic_repo):
        """Initialize restic repository."""

        env = {
            "RESTIC_REPOSITORY": str(temp_restic_repo),
            "RESTIC_PASSWORD": "test-password",
        }

        try:
            await exec_command(str(get_settings().restic_binary_path), "init", env=env)
        except (OSError, RuntimeError) as e:
            pytest.fail(f"Failed to initialize restic repository: {e}")

        return temp_restic_repo

    @pytest.fixture
    async def initialized_restic_repo_no_password(self, temp_restic_repo):
        """Initialize restic repository without password."""

        env = {
            "RESTIC_REPOSITORY": str(temp_restic_repo),
        }

        try:
            await exec_command(
                str(get_settings().restic_binary_path),
                "init",
                "--insecure-no-password",
                env=env,
            )
        except (OSError, RuntimeError) as e:
            pytest.fail(f"Failed to initialize restic repository without password: {e}")

        return temp_restic_repo

    @pytest.mark.asyncio
    async def test_create_server_snapshot_endpoint(
        self, client, mock_instance, initialized_restic_repo
    ):
        """Test creating a server snapshot via API endpoint."""
        server_id, instance = mock_instance

        with mock_snapshot_dependencies_setup(instance, initialized_restic_repo):
            response = client.post(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                json={"scope": _scope(server_id=server_id)},
            )

            assert response.status_code == 202
            data = task_result(client, response)

            # Verify response structure
            assert "snapshot" in data

            # Verify snapshot details
            snapshot = data["snapshot"]
            assert snapshot["id"] is not None
            assert len(snapshot["id"]) == 64  # SHA256 hash
            assert snapshot["short_id"] is not None
            assert len(snapshot["short_id"]) == 8
            assert len(snapshot["paths"]) > 0
            assert str(instance.project_path) in snapshot["paths"]

            # Verify summary information
            if snapshot.get("summary"):
                summary = snapshot["summary"]
                assert "total_files_processed" in summary
                assert summary["total_files_processed"] > 0
                assert "total_bytes_processed" in summary
                assert summary["total_bytes_processed"] > 0

    @pytest.mark.asyncio
    async def test_list_server_snapshots_endpoint(
        self, client, mock_instance, initialized_restic_repo
    ):
        """Test listing server snapshots via API endpoint."""
        server_id, instance = mock_instance

        with mock_snapshot_dependencies_setup(instance, initialized_restic_repo):
            # Create a snapshot first
            create_response = client.post(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                json={"scope": _scope(server_id=server_id)},
            )
            assert create_response.status_code == 202
            created_snapshot_id = task_result(client, create_response)["snapshot"]["id"]

            # List snapshots
            list_response = client.get(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                params={"server_id": server_id},
            )

            assert list_response.status_code == 200
            data = list_response.json()

            # Verify response structure
            assert "snapshots" in data
            assert len(data["snapshots"]) == 1

            # Verify snapshot details
            snapshot = data["snapshots"][0]
            assert snapshot["id"] == created_snapshot_id
            assert str(instance.project_path) in snapshot["paths"]

    @pytest.mark.asyncio
    async def test_snapshot_restore_preview_endpoint(
        self, client, mock_instance, initialized_restic_repo
    ):
        """Test snapshot restore preview via API endpoint."""
        server_id, instance = mock_instance

        with mock_snapshot_dependencies_setup(instance, initialized_restic_repo):
            # Create a snapshot
            create_response = client.post(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                json={"scope": _scope(server_id=server_id)},
            )
            assert create_response.status_code == 202
            snapshot_id = task_result(client, create_response)["snapshot"]["id"]

            # Modify some files to create changes
            (instance.get_data_path() / "server.properties").write_text(
                "server-port=25566\nmodified=true"
            )
            (instance.get_data_path() / "new_file.txt").write_text("This is a new file")

            # Preview restore
            preview_response = client.post(
                "/snapshots/previews",
                headers={"Authorization": "Bearer test_master_token"},
                json={"source_snapshot_id": snapshot_id, "scope": _scope(server_id, None)},
            )

            assert preview_response.status_code == 202
            data = _preview_result(client, preview_response)

            # Verify response structure
            assert "actions" in data
            assert "preview_summary" in data
            assert len(data["actions"]) > 0

            # Verify preview summary format - check for Chinese or English text patterns
            summary = data["preview_summary"]
            # Check if it contains either Chinese or English patterns for file operations
            has_file_operations = (
                "updated" in summary
                or "deleted" in summary
                or "restored" in summary
                or "更新" in summary
                or "删除" in summary
                or "恢复" in summary
            )
            assert has_file_operations, (
                f"Preview summary should contain file operation indicators: {summary}"
            )

            # Verify actions contain required fields; items are absolute on-disk paths
            for action in data["actions"]:
                assert "action" in action
                assert action["action"] in ["updated", "deleted", "restored"]
                assert "item" in action
                assert Path(action["item"]).is_absolute()
                assert "size" in action

    @pytest.mark.asyncio
    async def test_snapshot_restore_with_files_api_verification(
        self, client, mock_instance, initialized_restic_repo
    ):
        """Test actual snapshot restore and verify using files API endpoints."""
        server_id, instance = mock_instance

        with mock_snapshot_dependencies_setup(instance, initialized_restic_repo):
            # Record original file contents using files API
            original_props_response = client.get(
                f"/servers/{server_id}/files/content",
                headers={"Authorization": "Bearer test_master_token"},
                params={"path": "/server.properties"},
            )
            assert original_props_response.status_code == 200
            original_props_content = original_props_response.json()["content"]

            # List original files using files API (verify structure exists)
            original_files_response = client.get(
                f"/servers/{server_id}/files",
                headers={"Authorization": "Bearer test_master_token"},
            )
            assert original_files_response.status_code == 200
            assert len(original_files_response.json()["items"]) > 0

            # Create initial snapshot
            snapshot_response = client.post(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                json={"scope": _scope(server_id=server_id)},
            )
            assert snapshot_response.status_code == 202
            snapshot_id = task_result(client, snapshot_response)["snapshot"]["id"]

            # Modify files using files API
            modified_content = "# MODIFIED CONFIG\nserver-port=25566\nmax-players=10"
            modify_response = client.post(
                f"/servers/{server_id}/files/content",
                headers={"Authorization": "Bearer test_master_token"},
                params={"path": "/server.properties"},
                json={"content": modified_content},
            )
            assert modify_response.status_code == 200

            # Create new file using files API
            create_response = client.post(
                f"/servers/{server_id}/files/create",
                headers={"Authorization": "Bearer test_master_token"},
                json={"name": "new_config.yml", "type": "file", "path": "/"},
            )
            assert create_response.status_code == 200

            update_new_file_response = client.post(
                f"/servers/{server_id}/files/content",
                headers={"Authorization": "Bearer test_master_token"},
                params={"path": "/new_config.yml"},
                json={"content": "uploaded content"},
            )
            assert update_new_file_response.status_code == 200

            # Verify modifications
            modified_props_response = client.get(
                f"/servers/{server_id}/files/content",
                headers={"Authorization": "Bearer test_master_token"},
                params={"path": "/server.properties"},
            )
            assert modified_props_response.status_code == 200
            assert modified_props_response.json()["content"] != original_props_content

            # Get snapshot count before restore
            snapshots_before_restore = client.get(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                params={"server_id": server_id},
            )
            snapshot_count_before = len(snapshots_before_restore.json()["snapshots"])

            # Restore original snapshot (should automatically create a safety snapshot)
            restore_response = client.post(
                "/snapshots/restorations",
                headers={"Authorization": "Bearer test_master_token"},
                json={"source_snapshot_id": snapshot_id, "scope": _scope(server_id=server_id)},
            )
            assert restore_response.status_code == 202
            assert _restore_safety_snapshot_id(client, restore_response) is not None

            # Verify a new safety snapshot was created
            snapshots_after_restore = client.get(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                params={"server_id": server_id},
            )
            snapshot_count_after = len(snapshots_after_restore.json()["snapshots"])
            assert snapshot_count_after == snapshot_count_before + 1

            # Verify restoration using files API
            restored_props_response = client.get(
                f"/servers/{server_id}/files/content",
                headers={"Authorization": "Bearer test_master_token"},
                params={"path": "/server.properties"},
            )
            assert restored_props_response.status_code == 200
            restored_content = restored_props_response.json()["content"]
            assert restored_content == original_props_content

            # Verify created file was deleted
            created_file_response = client.get(
                f"/servers/{server_id}/files/content",
                headers={"Authorization": "Bearer test_master_token"},
                params={"path": "/new_config.yml"},
            )
            assert created_file_response.status_code == 404

    @pytest.mark.asyncio
    async def test_snapshot_path_filtering_endpoint(
        self, client, mock_instance, initialized_restic_repo
    ):
        """Test snapshot creation and listing with path filtering."""
        server_id, instance = mock_instance

        with mock_snapshot_dependencies_setup(instance, initialized_restic_repo):
            # Create snapshot of entire server
            full_snapshot_response = client.post(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                json={"scope": _scope(server_id=server_id)},
            )
            assert full_snapshot_response.status_code == 202
            full_snapshot_id = task_result(client, full_snapshot_response)["snapshot"]["id"]

            # Modify a file to ensure the next snapshot will be different
            await asyncio.sleep(0.2)
            (instance.get_data_path() / "server.properties").write_text(
                "# Modified config\nserver-port=25566"
            )

            # Create second snapshot of entire server (with changes)
            modified_snapshot_response = client.post(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                json={"scope": _scope(server_id=server_id)},
            )
            assert modified_snapshot_response.status_code == 202
            modified_snapshot_id = task_result(client, modified_snapshot_response)["snapshot"]["id"]

            # Verify snapshots have different IDs
            assert full_snapshot_id != modified_snapshot_id

            # List all snapshots for this server
            all_snapshots_response = client.get(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                params={"server_id": server_id},
            )
            assert all_snapshots_response.status_code == 200
            all_snapshots = all_snapshots_response.json()["snapshots"]
            all_snapshot_ids = {s["id"] for s in all_snapshots}

            # Should have exactly 2 snapshots
            assert len(all_snapshots) == 2
            assert full_snapshot_id in all_snapshot_ids
            assert modified_snapshot_id in all_snapshot_ids

            # Verify both snapshots have the same server path but different times
            for snapshot in all_snapshots:
                assert str(instance.project_path) in snapshot["paths"]

            # Test creating and listing a plugins-only snapshot separately
            await asyncio.sleep(0.2)
            (instance.get_data_path() / "plugins" / "test-plugin.jar").write_bytes(
                b"fake jar content"
            )

            plugins_snapshot_response = client.post(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                json={"scope": _scope(server_id=server_id, paths=["/plugins"])},
            )
            assert plugins_snapshot_response.status_code == 202
            plugins_snapshot_id = task_result(client, plugins_snapshot_response)["snapshot"]["id"]

            # List snapshots by plugins path - should only return snapshots containing plugins
            plugins_snapshots_response = client.get(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                params={"server_id": server_id, "path": "/plugins"},
            )
            assert plugins_snapshots_response.status_code == 200
            plugins_snapshots = plugins_snapshots_response.json()["snapshots"]

            # All three snapshots cover /plugins: the two full-server ones by
            # ancestor match, the plugins-only one by exact recorded path.
            plugins_snapshot_ids = {s["id"] for s in plugins_snapshots}
            assert full_snapshot_id in plugins_snapshot_ids, (
                "Full snapshot should be included (contains plugins)"
            )
            assert modified_snapshot_id in plugins_snapshot_ids, (
                "Modified snapshot should be included (contains plugins)"
            )
            assert plugins_snapshot_id in plugins_snapshot_ids, (
                "Plugins-only snapshot must match the /plugins filter exactly"
            )
            assert len(plugins_snapshot_ids) == 3

    @pytest.mark.asyncio
    async def test_snapshot_error_handling(
        self, client, mock_instance, initialized_restic_repo
    ):
        """Test error handling in snapshot endpoints."""
        server_id, instance = mock_instance

        with mock_snapshot_dependencies_setup(instance, initialized_restic_repo):
            invalid_restore_response = client.post(
                "/snapshots/restorations",
                headers={"Authorization": "Bearer test_master_token"},
                json={"source_snapshot_id": "0" * 64, "scope": _scope(server_id=server_id)},
            )
            assert invalid_restore_response.status_code == 202
            task = wait_task(client, invalid_restore_response, success=False)
            assert task["error"] == "服务器内部错误，请稍后重试"
            history = client.get("/snapshots/restorations", headers={"Authorization": "Bearer test_master_token"}).json()
            assert history["total"] == 1
            assert history["restorations"][0]["status"] == "failed"
            assert history["restorations"][0]["safety_snapshot_id"] is None

            preview = client.post(
                "/snapshots/previews",
                headers={"Authorization": "Bearer test_master_token"},
                json={"source_snapshot_id": 'invalid-snapshot-id', "scope": _scope(server_id, None)},
            )
            assert preview.status_code == 422
            assert preview.json()["detail"]

    @pytest.mark.asyncio
    async def test_unauthorized_access(
        self, client, mock_instance, initialized_restic_repo
    ):
        """Test unauthorized access to snapshot endpoints."""
        server_id, instance = mock_instance

        with mock_snapshot_dependencies_setup(instance, initialized_restic_repo):
            # Test without authorization header
            response = client.post("/snapshots", json={"scope": _scope(server_id=server_id)})
            assert response.status_code in [401, 422]

            # Test with invalid token
            response = client.post(
                "/snapshots",
                headers={"Authorization": "Bearer invalid_token"},
                json={"scope": _scope(server_id=server_id)},
            )
            assert response.status_code in [401, 422]

    @pytest.mark.asyncio
    async def test_comprehensive_mc_server_restore_integrity(
        self, client, mock_instance, initialized_restic_repo
    ):
        """Test comprehensive MC server file integrity after restore."""
        server_id, instance = mock_instance

        with mock_snapshot_dependencies_setup(instance, initialized_restic_repo):
            # Capture original MC server structure using files API
            original_structure = {}

            # Get root directory listing
            root_response = client.get(
                f"/servers/{server_id}/files",
                headers={"Authorization": "Bearer test_master_token"},
            )
            assert root_response.status_code == 200

            # Recursively capture file contents for key MC files
            key_files = [
                "/server.properties",
                "/bukkit.yml",
                "/paper.yml",
                "/plugins/Essentials/config.yml",
            ]

            for file_path in key_files:
                file_response = client.get(
                    f"/servers/{server_id}/files/content",
                    headers={"Authorization": "Bearer test_master_token"},
                    params={"path": file_path},
                )
                if file_response.status_code == 200:
                    original_structure[file_path] = file_response.json()["content"]

            # Create snapshot of entire server
            snapshot_response = client.post(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                json={"scope": _scope(server_id=server_id)},
            )
            assert snapshot_response.status_code == 202
            snapshot_id = task_result(client, snapshot_response)["snapshot"]["id"]

            # Simulate server modifications (corrupt configs, add unwanted files)
            corrupted_props = "# CORRUPTED\nserver-port=invalid\nmax-players=999999"
            corrupt_response = client.post(
                f"/servers/{server_id}/files/content",
                headers={"Authorization": "Bearer test_master_token"},
                params={"path": "/server.properties"},
                json={"content": corrupted_props},
            )
            assert corrupt_response.status_code == 200

            # Add unwanted files
            create_unwanted_response = client.post(
                f"/servers/{server_id}/files/create",
                headers={"Authorization": "Bearer test_master_token"},
                json={"name": "malware.exe", "type": "file", "path": "/"},
            )
            assert create_unwanted_response.status_code == 200

            # Delete important files
            delete_response = client.delete(
                f"/servers/{server_id}/files",
                headers={"Authorization": "Bearer test_master_token"},
                params={"path": "/bukkit.yml"},
            )
            wait_task(client, delete_response)

            # Confirm the damage actually happened before restoring.
            assert (
                instance.get_data_path() / "server.properties"
            ).read_text() == corrupted_props
            assert (instance.get_data_path() / "malware.exe").exists()
            assert not (instance.get_data_path() / "bukkit.yml").exists()

            # Restore (will automatically create safety snapshot)
            restore_response = client.post(
                "/snapshots/restorations",
                headers={"Authorization": "Bearer test_master_token"},
                json={"source_snapshot_id": snapshot_id, "scope": _scope(server_id=server_id)},
            )
            assert restore_response.status_code == 202
            assert _restore_safety_snapshot_id(client, restore_response) is not None

            # Verify complete restoration using files API
            for file_path, expected_content in original_structure.items():
                restored_response = client.get(
                    f"/servers/{server_id}/files/content",
                    headers={"Authorization": "Bearer test_master_token"},
                    params={"path": file_path},
                )
                assert restored_response.status_code == 200
                restored_content = restored_response.json()["content"]
                assert restored_content == expected_content

            # Verify unwanted files were removed
            malware_response = client.get(
                f"/servers/{server_id}/files/content",
                headers={"Authorization": "Bearer test_master_token"},
                params={"path": "/malware.exe"},
            )
            assert malware_response.status_code == 404

    @pytest.mark.asyncio
    async def test_partial_restore_scope_verification(
        self, client, mock_instance, initialized_restic_repo
    ):
        """Test that partial restore only affects specified subdirectory, not other areas."""
        server_id, instance = mock_instance

        with mock_snapshot_dependencies_setup(instance, initialized_restic_repo):
            # Record original content from both subdirectory and root directory
            plugins_config_original = client.get(
                f"/servers/{server_id}/files/content",
                headers={"Authorization": "Bearer test_master_token"},
                params={"path": "/plugins/Essentials/config.yml"},
            )
            assert plugins_config_original.status_code == 200
            plugins_original_content = plugins_config_original.json()["content"]

            # Verify server.properties exists (we'll verify it remains modified later)
            server_props_original = client.get(
                f"/servers/{server_id}/files/content",
                headers={"Authorization": "Bearer test_master_token"},
                params={"path": "/server.properties"},
            )
            assert server_props_original.status_code == 200

            # Create initial snapshot
            snapshot_response = client.post(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                json={"scope": _scope(server_id=server_id)},
            )
            assert snapshot_response.status_code == 202
            snapshot_id = task_result(client, snapshot_response)["snapshot"]["id"]

            # Modify files in both subdirectory (plugins) and root directory (data)
            # 1. Modify file in plugins subdirectory
            plugins_modified_content = """# MODIFIED PLUGINS CONFIG
essentials:
  command-cooldowns:
    home: 30
    tpa: 15
  modified: true
"""
            plugins_modify_response = client.post(
                f"/servers/{server_id}/files/content",
                headers={"Authorization": "Bearer test_master_token"},
                params={"path": "/plugins/Essentials/config.yml"},
                json={"content": plugins_modified_content},
            )
            assert plugins_modify_response.status_code == 200

            # 2. Modify file in root data directory
            server_props_modified_content = """# MODIFIED SERVER CONFIG
server-port=25567
gamemode=creative
difficulty=hard
max-players=50
modified=true
"""
            server_props_modify_response = client.post(
                f"/servers/{server_id}/files/content",
                headers={"Authorization": "Bearer test_master_token"},
                params={"path": "/server.properties"},
                json={"content": server_props_modified_content},
            )
            assert server_props_modify_response.status_code == 200

            # Verify both files are modified
            plugins_check = client.get(
                f"/servers/{server_id}/files/content",
                headers={"Authorization": "Bearer test_master_token"},
                params={"path": "/plugins/Essentials/config.yml"},
            )
            assert plugins_check.status_code == 200
            assert plugins_check.json()["content"] == plugins_modified_content

            server_props_check = client.get(
                f"/servers/{server_id}/files/content",
                headers={"Authorization": "Bearer test_master_token"},
                params={"path": "/server.properties"},
            )
            assert server_props_check.status_code == 200
            assert server_props_check.json()["content"] == server_props_modified_content

            # Create a file in /world after the snapshot but before the
            # restore: a plugins-only restore must leave it untouched even
            # though it doesn't exist in the snapshot.
            world_test_content = "This file should not be affected by plugins restore"
            world_create_response = client.post(
                f"/servers/{server_id}/files/create",
                headers={"Authorization": "Bearer test_master_token"},
                json={
                    "name": "test_after_snapshot.txt",
                    "type": "file",
                    "path": "/world",
                },
            )
            assert world_create_response.status_code == 200
            world_content_response = client.post(
                f"/servers/{server_id}/files/content",
                headers={"Authorization": "Bearer test_master_token"},
                params={"path": "/world/test_after_snapshot.txt"},
                json={"content": world_test_content},
            )
            assert world_content_response.status_code == 200

            # Restore ONLY the plugins subdirectory to the original snapshot
            # (will automatically create safety snapshot)
            restore_response = client.post(
                "/snapshots/restorations",
                headers={"Authorization": "Bearer test_master_token"},
                json={"source_snapshot_id": snapshot_id, "scope": _scope(server_id=server_id, paths=["/plugins"])},
            )
            assert restore_response.status_code == 202
            assert _restore_safety_snapshot_id(client, restore_response) is not None

            # Verify plugins subdirectory was restored to original state
            plugins_restored_check = client.get(
                f"/servers/{server_id}/files/content",
                headers={"Authorization": "Bearer test_master_token"},
                params={"path": "/plugins/Essentials/config.yml"},
            )
            assert plugins_restored_check.status_code == 200
            assert (
                plugins_restored_check.json()["content"] == plugins_original_content
            ), "Plugins config should be restored to original state"

            # Verify root directory file was NOT affected by partial restore
            server_props_final_check = client.get(
                f"/servers/{server_id}/files/content",
                headers={"Authorization": "Bearer test_master_token"},
                params={"path": "/server.properties"},
            )
            assert server_props_final_check.status_code == 200
            assert (
                server_props_final_check.json()["content"]
                == server_props_modified_content
            ), (
                "Server properties should remain modified (not affected by plugins-only restore)"
            )

            # The /world file created after the snapshot survived the
            # plugins-only restore — proof the restore never touched /world.
            world_final_check = client.get(
                f"/servers/{server_id}/files/content",
                headers={"Authorization": "Bearer test_master_token"},
                params={"path": "/world/test_after_snapshot.txt"},
            )
            assert world_final_check.status_code == 200, (
                "Files in other subdirectories should not be affected by plugins-only restore"
            )
            assert world_final_check.json()["content"] == world_test_content

    @pytest.mark.asyncio
    async def test_create_snapshot_no_password(
        self, client, mock_instance, initialized_restic_repo_no_password
    ):
        """Test creating a snapshot with no password repository."""
        server_id, instance = mock_instance

        with mock_snapshot_dependencies_setup(
            instance, initialized_restic_repo_no_password, restic_password=None
        ):
            response = client.post(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                json={"scope": _scope(server_id=server_id)},
            )

            assert response.status_code == 202
            data = task_result(client, response)

            # Verify response structure
            assert "snapshot" in data

            # Verify snapshot details
            snapshot = data["snapshot"]
            assert snapshot["id"] is not None
            assert len(snapshot["id"]) == 64  # SHA256 hash
            assert snapshot["short_id"] is not None
            assert len(snapshot["short_id"]) == 8
            assert len(snapshot["paths"]) > 0
            assert str(instance.project_path) in snapshot["paths"]

    @pytest.mark.asyncio
    async def test_list_snapshots_no_password(
        self, client, mock_instance, initialized_restic_repo_no_password
    ):
        """Test listing snapshots with no password repository."""
        server_id, instance = mock_instance

        with mock_snapshot_dependencies_setup(
            instance, initialized_restic_repo_no_password, restic_password=None
        ):
            # Create a snapshot first
            create_response = client.post(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                json={"scope": _scope(server_id=server_id)},
            )
            assert create_response.status_code == 202
            created_snapshot_id = task_result(client, create_response)["snapshot"]["id"]

            # List snapshots
            list_response = client.get(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                params={"server_id": server_id},
            )

            assert list_response.status_code == 200
            data = list_response.json()

            # Verify response structure
            assert "snapshots" in data
            assert len(data["snapshots"]) == 1

            # Verify snapshot details
            snapshot = data["snapshots"][0]
            assert snapshot["id"] == created_snapshot_id
            assert str(instance.project_path) in snapshot["paths"]

    @pytest.mark.asyncio
    async def test_restore_preview_no_password(
        self, client, mock_instance, initialized_restic_repo_no_password
    ):
        """Test restore preview with no password repository."""
        server_id, instance = mock_instance

        with mock_snapshot_dependencies_setup(
            instance, initialized_restic_repo_no_password, restic_password=None
        ):
            # Create a snapshot
            create_response = client.post(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                json={"scope": _scope(server_id=server_id)},
            )
            assert create_response.status_code == 202
            snapshot_id = task_result(client, create_response)["snapshot"]["id"]

            # Modify some files to create changes
            (instance.get_data_path() / "server.properties").write_text(
                "server-port=25566\nmodified=true"
            )
            (instance.get_data_path() / "new_file.txt").write_text("This is a new file")

            # Preview restore
            preview_response = client.post(
                "/snapshots/previews",
                headers={"Authorization": "Bearer test_master_token"},
                json={"source_snapshot_id": snapshot_id, "scope": _scope(server_id, None)},
            )

            assert preview_response.status_code == 202
            data = _preview_result(client, preview_response)

            # Verify response structure
            assert "actions" in data
            assert "preview_summary" in data
            assert len(data["actions"]) > 0

    @pytest.mark.asyncio
    async def test_restore_no_password(
        self, client, mock_instance, initialized_restic_repo_no_password
    ):
        """Test actual restore with no password repository."""
        server_id, instance = mock_instance

        with mock_snapshot_dependencies_setup(
            instance, initialized_restic_repo_no_password, restic_password=None
        ):
            # Record original file content
            original_props_response = client.get(
                f"/servers/{server_id}/files/content",
                headers={"Authorization": "Bearer test_master_token"},
                params={"path": "/server.properties"},
            )
            assert original_props_response.status_code == 200
            original_props_content = original_props_response.json()["content"]

            # Create initial snapshot
            snapshot_response = client.post(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                json={"scope": _scope(server_id=server_id)},
            )
            assert snapshot_response.status_code == 202
            snapshot_id = task_result(client, snapshot_response)["snapshot"]["id"]

            # Modify file
            modified_content = "# MODIFIED CONFIG\nserver-port=25566\nmax-players=10"
            modify_response = client.post(
                f"/servers/{server_id}/files/content",
                headers={"Authorization": "Bearer test_master_token"},
                params={"path": "/server.properties"},
                json={"content": modified_content},
            )
            assert modify_response.status_code == 200

            # Restore (will automatically create safety snapshot)
            restore_response = client.post(
                "/snapshots/restorations",
                headers={"Authorization": "Bearer test_master_token"},
                json={"source_snapshot_id": snapshot_id, "scope": _scope(server_id=server_id)},
            )
            assert restore_response.status_code == 202
            assert _restore_safety_snapshot_id(client, restore_response) is not None

            # Verify restoration
            restored_props_response = client.get(
                f"/servers/{server_id}/files/content",
                headers={"Authorization": "Bearer test_master_token"},
                params={"path": "/server.properties"},
            )
            assert restored_props_response.status_code == 200
            restored_content = restored_props_response.json()["content"]
            assert restored_content == original_props_content

    @pytest.mark.asyncio
    async def test_no_password_empty_string(
        self, client, mock_instance, initialized_restic_repo_no_password
    ):
        """Test that empty string password is treated as no password."""
        server_id, instance = mock_instance

        with mock_snapshot_dependencies_setup(
            instance, initialized_restic_repo_no_password, restic_password=""
        ):
            response = client.post(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                json={"scope": _scope(server_id=server_id)},
            )

            assert response.status_code == 202
            task_result(client, response)

    @pytest.mark.asyncio
    async def test_delete_snapshot(
        self, client, mock_instance, initialized_restic_repo
    ):
        """Test deleting a specific snapshot by ID."""
        server_id, instance = mock_instance

        with mock_snapshot_dependencies_setup(instance, initialized_restic_repo):
            # Create first snapshot
            snapshot1_response = client.post(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                json={"scope": _scope(server_id=server_id)},
            )
            assert snapshot1_response.status_code == 202
            snapshot1_id = task_result(client, snapshot1_response)["snapshot"]["id"]

            # Modify a file to ensure the next snapshot will be different
            await asyncio.sleep(0.2)
            (instance.get_data_path() / "server.properties").write_text(
                "# Modified config\nserver-port=25566"
            )

            # Create second snapshot
            snapshot2_response = client.post(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                json={"scope": _scope(server_id=server_id)},
            )
            assert snapshot2_response.status_code == 202
            snapshot2_id = task_result(client, snapshot2_response)["snapshot"]["id"]

            # Verify both snapshots exist
            list_response = client.get(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                params={"server_id": server_id},
            )
            assert list_response.status_code == 200
            snapshots = list_response.json()["snapshots"]
            assert len(snapshots) == 2
            snapshot_ids = {s["id"] for s in snapshots}
            assert snapshot1_id in snapshot_ids
            assert snapshot2_id in snapshot_ids

            # Delete first snapshot
            delete_response = client.delete(
                f"/snapshots/{snapshot1_id}",
                headers={"Authorization": "Bearer test_master_token"},
            )
            assert delete_response.status_code == 202
            assert "已删除" in task_result(client, delete_response)["message"]

            # Verify only second snapshot remains
            list_after_delete = client.get(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                params={"server_id": server_id},
            )
            assert list_after_delete.status_code == 200
            remaining_snapshots = list_after_delete.json()["snapshots"]
            assert len(remaining_snapshots) == 1
            assert remaining_snapshots[0]["id"] == snapshot2_id

    @pytest.mark.asyncio
    async def test_multi_path_create_preview_and_restore_endpoint(
        self, client, mock_instance, initialized_restic_repo
    ):
        """Create a snapshot covering multiple data paths, then preview and restore them in one call."""
        server_id, instance = mock_instance

        with mock_snapshot_dependencies_setup(instance, initialized_restic_repo):
            # Add an extra plugin file so /plugins changes meaningfully on restore
            (instance.get_data_path() / "plugins" / "first.jar").write_bytes(b"first")

            # Snapshot covering /plugins + /world together
            create_response = client.post(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                json={"scope": _scope(server_id=server_id, paths=["/plugins", "/world"])},
            )
            assert create_response.status_code == 202
            snapshot = task_result(client, create_response)["snapshot"]
            snapshot_id = snapshot["id"]

            data_path = instance.get_data_path()
            assert str((data_path / "plugins").resolve()) in snapshot["paths"]
            assert str((data_path / "world").resolve()) in snapshot["paths"]

            # Mutate both included roots and a sibling that must remain untouched
            (instance.get_data_path() / "plugins" / "intruder.jar").write_bytes(
                b"intruder"
            )
            (instance.get_data_path() / "world" / "intruder.txt").write_text(
                "should be deleted"
            )
            untouched_path = instance.get_data_path() / "server.properties"
            untouched_original = untouched_path.read_text()
            untouched_path.write_text("# untouched marker\nserver-port=25600")

            # Preview reports actions for both roots
            preview_response = client.post(
                "/snapshots/previews",
                headers={"Authorization": "Bearer test_master_token"},
                json={"source_snapshot_id": snapshot_id, "scope": _scope(server_id, ['/plugins', '/world'])},
            )
            assert preview_response.status_code == 202
            actions = _preview_result(client, preview_response)["actions"]
            items = [a.get("item", "") for a in actions]
            assert any(str(data_path / "plugins") in item for item in items)
            assert any(str(data_path / "world") in item for item in items)

            # Restore both included roots in one call
            restore_response = client.post(
                "/snapshots/restorations",
                headers={"Authorization": "Bearer test_master_token"},
                json={"source_snapshot_id": snapshot_id, "scope": _scope(server_id=server_id, paths=["/plugins", "/world"])},
            )
            assert restore_response.status_code == 202
            assert _restore_safety_snapshot_id(client, restore_response) is not None

            # Intruders inside both included roots are gone
            assert not (
                instance.get_data_path() / "plugins" / "intruder.jar"
            ).exists()
            assert not (
                instance.get_data_path() / "world" / "intruder.txt"
            ).exists()

            # File outside the included roots is preserved (not touched by restore)
            assert untouched_path.read_text() != untouched_original
            assert untouched_path.read_text().startswith("# untouched marker")

    @pytest.mark.asyncio
    async def test_delete_snapshot_unauthorized(
        self, client, mock_instance, initialized_restic_repo
    ):
        """Test deleting a snapshot without authorization."""
        server_id, instance = mock_instance

        with mock_snapshot_dependencies_setup(instance, initialized_restic_repo):
            # Create a snapshot first
            snapshot_response = client.post(
                "/snapshots",
                headers={"Authorization": "Bearer test_master_token"},
                json={"scope": _scope(server_id=server_id)},
            )
            assert snapshot_response.status_code == 202
            snapshot_id = task_result(client, snapshot_response)["snapshot"]["id"]

            # Try to delete without authorization
            delete_response = client.delete(f"/snapshots/{snapshot_id}")
            assert delete_response.status_code in [401, 422]


class TestIgnoredPathsEndpoints:
    """API tests for ignored_paths behavior: excluded from backups, never
    overwritten or deleted by restores."""

    @pytest.fixture
    def client(self):
        with TestClient(api_app) as client:
            yield client

    @pytest.fixture
    def temp_server_dir(self):
        with tempfile.TemporaryDirectory(prefix="mc_ignored_test_") as temp_dir:
            yield Path(temp_dir)

    @pytest.fixture
    def temp_restic_repo(self):
        with tempfile.TemporaryDirectory(prefix="restic_repo_ignored_") as temp_dir:
            yield Path(temp_dir)

    @pytest.fixture
    def mock_instance(self, temp_server_dir):
        server_id = "test_server"
        instance = MockMCInstance(server_id, temp_server_dir)
        instance.setup_mc_server_structure()
        # Tile cache the ignore config protects (level-name defaults to world).
        mcmap = instance.get_data_path() / ".mcmap" / "tiles"
        mcmap.mkdir(parents=True)
        (mcmap / "r.0.0.png").write_bytes(b"tile")
        return server_id, instance

    @pytest.fixture
    async def initialized_restic_repo(self, temp_restic_repo):
        env = {
            "RESTIC_REPOSITORY": str(temp_restic_repo),
            "RESTIC_PASSWORD": "test-password",
        }
        await exec_command(str(get_settings().restic_binary_path), "init", env=env)
        return temp_restic_repo

    def _auth(self):
        return {"Authorization": "Bearer test_master_token"}

    def test_create_snapshot_records_excludes(
        self, client, mock_instance, initialized_restic_repo
    ):
        server_id, instance = mock_instance
        data_path = instance.get_data_path()

        with mock_snapshot_dependencies_setup(
            instance, initialized_restic_repo, ignored_paths=[".mcmap", "cache"]
        ):
            response = client.post(
                "/snapshots", headers=self._auth(), json={"scope": _scope(server_id=server_id)}
            )
            assert response.status_code == 202
            excludes = task_result(client, response)["snapshot"]["excludes"]
            assert sorted(excludes) == [
                str((data_path / ".mcmap").resolve()),
                str((data_path / "cache").resolve()),
            ]

    def test_restore_preserves_ignored_paths(
        self, client, mock_instance, initialized_restic_repo
    ):
        """End-to-end: ignored paths survive a full-server restore with
        --delete while everything else reverts."""
        server_id, instance = mock_instance
        data_path = instance.get_data_path()

        with mock_snapshot_dependencies_setup(
            instance, initialized_restic_repo, ignored_paths=[".mcmap", "cache"]
        ):
            create_response = client.post(
                "/snapshots", headers=self._auth(), json={"scope": _scope(server_id=server_id)}
            )
            assert create_response.status_code == 202
            snapshot_id = task_result(client, create_response)["snapshot"]["id"]

            # Mutate: config corruption, extraneous file, ignored-path growth.
            properties = data_path / "server.properties"
            original_properties = properties.read_text()
            properties.write_text("# corrupted\n")
            extraneous = data_path / "uploaded.bin"
            extraneous.write_bytes(b"junk")
            tile = data_path / ".mcmap" / "tiles" / "r.0.0.png"
            tile.write_bytes(b"tile-rendered-after-snapshot")
            new_cache = data_path / "cache" / "new_download.jar"
            new_cache.write_bytes(b"downloaded-after-snapshot")

            restore_response = client.post(
                "/snapshots/restorations",
                headers=self._auth(),
                json={"source_snapshot_id": snapshot_id, "scope": _scope(server_id=server_id)},
            )
            assert restore_response.status_code == 202
            assert _restore_safety_snapshot_id(client, restore_response) is not None

            assert properties.read_text() == original_properties
            assert not extraneous.exists()
            assert tile.read_bytes() == b"tile-rendered-after-snapshot"
            assert new_cache.read_bytes() == b"downloaded-after-snapshot"

    def test_safety_snapshot_also_excludes_ignored_paths(
        self, client, mock_instance, initialized_restic_repo
    ):
        server_id, instance = mock_instance

        with mock_snapshot_dependencies_setup(
            instance, initialized_restic_repo, ignored_paths=[".mcmap"]
        ):
            create_response = client.post(
                "/snapshots", headers=self._auth(), json={"scope": _scope(server_id=server_id)}
            )
            snapshot_id = task_result(client, create_response)["snapshot"]["id"]

            restore_response = client.post(
                "/snapshots/restorations",
                headers=self._auth(),
                json={"source_snapshot_id": snapshot_id, "scope": _scope(server_id=server_id)},
            )
            safety_id = _restore_safety_snapshot_id(client, restore_response)

            list_response = client.get("/snapshots", headers=self._auth())
            safety = next(
                s
                for s in list_response.json()["snapshots"]
                if s["id"] == safety_id
            )
            assert safety["excludes"] == [
                str((instance.get_data_path() / ".mcmap").resolve())
            ]

    def test_preview_reports_nothing_for_ignored_paths(
        self, client, mock_instance, initialized_restic_repo
    ):
        server_id, instance = mock_instance
        data_path = instance.get_data_path()

        with mock_snapshot_dependencies_setup(
            instance, initialized_restic_repo, ignored_paths=[".mcmap"]
        ):
            create_response = client.post(
                "/snapshots", headers=self._auth(), json={"scope": _scope(server_id=server_id)}
            )
            snapshot_id = task_result(client, create_response)["snapshot"]["id"]

            (data_path / ".mcmap" / "tiles" / "r.0.1.png").write_bytes(b"new-tile")
            (data_path / "extraneous.txt").write_text("x")

            preview_response = client.post(
                "/snapshots/previews",
                headers=self._auth(),
                json={"source_snapshot_id": snapshot_id, "scope": _scope(server_id, None)},
            )
            assert preview_response.status_code == 202
            actions = _preview_result(client, preview_response)["actions"]
            items = [a["item"] for a in actions]
            assert str(data_path / "extraneous.txt") in items
            assert not any(".mcmap" in item for item in items)

    def test_create_snapshot_of_ignored_path_rejected(
        self, client, mock_instance, initialized_restic_repo
    ):
        server_id, instance = mock_instance

        with mock_snapshot_dependencies_setup(
            instance, initialized_restic_repo, ignored_paths=["cache"]
        ):
            response = client.post(
                "/snapshots",
                headers=self._auth(),
                json={"scope": _scope(server_id=server_id, paths=["/cache"])},
            )
            assert response.status_code == 400
            assert "忽略" in response.json()["detail"]

    def test_preview_of_ignored_path_rejected(
        self, client, mock_instance, initialized_restic_repo
    ):
        server_id, instance = mock_instance

        with mock_snapshot_dependencies_setup(
            instance, initialized_restic_repo, ignored_paths=["cache"]
        ):
            create_response = client.post(
                "/snapshots", headers=self._auth(), json={"scope": _scope(server_id=server_id)}
            )
            snapshot_id = task_result(client, create_response)["snapshot"]["id"]

            response = client.post(
                "/snapshots/previews",
                headers=self._auth(),
                json={"source_snapshot_id": snapshot_id, "scope": _scope(server_id, ['/cache'])},
            )
            assert response.status_code == 400
            assert "忽略" in response.json()["detail"]

    def test_restore_of_ignored_path_is_rejected_before_acceptance(
        self, client, mock_instance, initialized_restic_repo
    ):
        """Ignored targets never create a task or modify live content."""
        server_id, instance = mock_instance
        data_path = instance.get_data_path()

        with mock_snapshot_dependencies_setup(
            instance, initialized_restic_repo, ignored_paths=["cache"]
        ):
            create_response = client.post(
                "/snapshots", headers=self._auth(), json={"scope": _scope(server_id=server_id)}
            )
            snapshot_id = task_result(client, create_response)["snapshot"]["id"]

            marker = data_path / "cache" / "mojang_1.20.4.jar"
            before = marker.read_bytes()

            response = client.post(
                "/snapshots/restorations",
                headers=self._auth(),
                json={"source_snapshot_id": snapshot_id, "scope": _scope(server_id=server_id, paths=["/cache"])},
            )
            assert response.status_code == 400
            assert "忽略" in response.json()["detail"]
            assert marker.read_bytes() == before

    def test_list_filter_excludes_snapshots_that_ignored_the_path(
        self, client, mock_instance, initialized_restic_repo
    ):
        """A snapshot taken while a path was ignored must not be listed as
        covering that path."""
        server_id, instance = mock_instance

        with mock_snapshot_dependencies_setup(
            instance, initialized_restic_repo, ignored_paths=["cache"]
        ):
            create_response = client.post(
                "/snapshots", headers=self._auth(), json={"scope": _scope(server_id=server_id)}
            )
            assert create_response.status_code == 202
            snapshot_id = task_result(client, create_response)["snapshot"]["id"]

            cache_filtered = client.get(
                "/snapshots",
                headers=self._auth(),
                params={"server_id": server_id, "path": "/cache"},
            )
            assert cache_filtered.status_code == 200
            assert snapshot_id not in {
                s["id"] for s in cache_filtered.json()["snapshots"]
            }

            plugins_filtered = client.get(
                "/snapshots",
                headers=self._auth(),
                params={"server_id": server_id, "path": "/plugins"},
            )
            assert plugins_filtered.status_code == 200
            assert snapshot_id in {
                s["id"] for s in plugins_filtered.json()["snapshots"]
            }

    def test_level_name_token_via_api(
        self, client, mock_instance, initialized_restic_repo
    ):
        """<LEVEL_NAME> expands against server.properties (level-name=world
        in the mock structure)."""
        server_id, instance = mock_instance
        data_path = instance.get_data_path()

        with mock_snapshot_dependencies_setup(
            instance,
            initialized_restic_repo,
            ignored_paths=["<LEVEL_NAME>/session.lock"],
        ):
            create_response = client.post(
                "/snapshots", headers=self._auth(), json={"scope": _scope(server_id=server_id)}
            )
            assert create_response.status_code == 202
            snapshot_id = task_result(client, create_response)["snapshot"]["id"]
            assert task_result(client, create_response)["snapshot"]["excludes"] == [
                str((data_path / "world" / "session.lock").resolve())
            ]

            lock = data_path / "world" / "session.lock"
            lock.write_bytes(b"\xff" * 8)

            restore_response = client.post(
                "/snapshots/restorations",
                headers=self._auth(),
                json={"source_snapshot_id": snapshot_id, "scope": _scope(server_id=server_id)},
            )
            assert restore_response.status_code == 202
            assert _restore_safety_snapshot_id(client, restore_response) is not None
            assert lock.read_bytes() == b"\xff" * 8


if __name__ == "__main__":
    pytest.main([__file__, "-v"])


class TestPathContainmentEndpoints:
    """Traversal and symlink escapes in snapshot requests must be rejected
    before any restic invocation."""

    @pytest.fixture
    def client(self):
        with TestClient(api_app) as client:
            yield client

    @pytest.fixture
    def temp_server_dir(self):
        with tempfile.TemporaryDirectory(prefix="mc_containment_test_") as temp_dir:
            yield Path(temp_dir)

    @pytest.fixture
    def temp_restic_repo(self):
        with tempfile.TemporaryDirectory(prefix="restic_repo_containment_") as temp_dir:
            yield Path(temp_dir)

    @pytest.fixture
    def mock_instance(self, temp_server_dir):
        server_id = "test_server"
        instance = MockMCInstance(server_id, temp_server_dir)
        instance.setup_mc_server_structure()
        return server_id, instance

    @pytest.fixture
    async def initialized_restic_repo(self, temp_restic_repo):
        env = {
            "RESTIC_REPOSITORY": str(temp_restic_repo),
            "RESTIC_PASSWORD": "test-password",
        }
        await exec_command(str(get_settings().restic_binary_path), "init", env=env)
        return temp_restic_repo

    def _auth(self):
        return {"Authorization": "Bearer test_master_token"}

    @pytest.mark.parametrize(
        "escape_path",
        ["../escape", "/../escape", "a/../../escape", "../../etc/passwd"],
    )
    def test_paths_traversal_rejected(
        self, client, mock_instance, initialized_restic_repo, escape_path
    ):
        server_id, instance = mock_instance
        outside = instance.base_path.parent / "escape"
        outside.mkdir(exist_ok=True)
        (outside / "victim.txt").write_text("do not touch")

        with mock_snapshot_dependencies_setup(instance, initialized_restic_repo):
            for endpoint, payload in [
                ("/snapshots", {"scope": _scope(server_id, [escape_path])}),
                (
                    "/snapshots/previews",
                    {
                        "source_snapshot_id": "0" * 64,
                        "scope": _scope(server_id, [escape_path]),
                    },
                ),
                (
                    "/snapshots/restorations",
                    {
                        "source_snapshot_id": "0" * 64,
                        "scope": _scope(server_id, [escape_path]),
                    },
                ),
            ]:
                response = client.post(endpoint, headers=self._auth(), json=payload)
                assert response.status_code == 422, (
                    f"{endpoint} accepted escaping path {escape_path!r}"
                )
                assert response.json()["detail"]
        assert (outside / "victim.txt").read_text() == "do not touch"

    def test_server_id_traversal_rejected(
        self, client, mock_instance, initialized_restic_repo
    ):
        """server_id is joined into the project path, so it traverses too."""
        from app.minecraft.instance import MCInstance

        _server_id, instance = mock_instance
        outside = instance.base_path.parent / "other"
        outside.mkdir(exist_ok=True)

        with mock_snapshot_dependencies_setup(instance, initialized_restic_repo):
            with patch.object(current_runtime().docker_mc_manager, 'get_instance', side_effect=lambda sid: MCInstance(instance.base_path, sid)):
                response = client.post(
                    "/snapshots",
                    headers=self._auth(),
                    json={"scope": _scope(server_id="../other")},
                )
            assert response.status_code == 400
            assert response.json()["detail"] == "服务器名称必须是有效的单级目录名称"

    def test_symlink_escape_rejected(
        self, client, mock_instance, initialized_restic_repo
    ):
        server_id, instance = mock_instance
        outside = instance.base_path.parent / "outside"
        outside.mkdir(exist_ok=True)
        (instance.get_data_path() / "escape_link").symlink_to(outside)

        with mock_snapshot_dependencies_setup(instance, initialized_restic_repo):
            response = client.post(
                "/snapshots",
                headers=self._auth(),
                json={"scope": _scope(server_id=server_id, paths=["/escape_link"])},
            )
            assert response.status_code == 400
            assert "目录" in response.json()["detail"]

    def test_symlink_inside_data_dir_allowed(
        self, client, mock_instance, initialized_restic_repo
    ):
        server_id, instance = mock_instance
        (instance.get_data_path() / "world_alias").symlink_to(
            instance.get_data_path() / "world"
        )

        with mock_snapshot_dependencies_setup(instance, initialized_restic_repo):
            response = client.post(
                "/snapshots",
                headers=self._auth(),
                json={"scope": _scope(server_id=server_id, paths=["/world_alias"])},
            )
            assert response.status_code == 202

            task_result(client, response)

pytestmark = [pytestmark, pytest.mark.binary('restic')]
